# Generated by Django 5.0.6 on 2025-11-02 21:10

from django.db import migrations, models


def copy_times_to_hours(apps, schema_editor):
    Restaurant = apps.get_model("restaurants", "Restaurant")
    weekdays = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
    for restaurant in Restaurant.objects.all():
        opening = getattr(restaurant, "opening_time", None)
        closing = getattr(restaurant, "closing_time", None)
        if opening and closing:
            block = {
                day: {
                    "open": opening.strftime("%H:%M"),
                    "close": closing.strftime("%H:%M"),
                }
                for day in weekdays
            }
        else:
            block = {}
        restaurant.opening_hours = block
        restaurant.save(update_fields=["opening_hours"])


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0002_remove_restaurant_opening_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="opening_hours",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(copy_times_to_hours, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="restaurant",
            name="closing_time",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="opening_time",
        ),
    ]
