# Generated by Django 5.0.6 on 2025-11-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0004_reservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("CANCELLED", "Cancelled"),
                    ("DECLINED", "Declined"),
                ],
                default="PENDING",
                max_length=16,
            ),
        ),
    ]
