# Generated by Django 5.1.14 on 2025-11-16 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0005_alter_reservation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="rating",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                help_text="Average rating shown to users (0.0–5.0).",
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
