# Generated by Django 5.1.14 on 2025-11-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0006_alter_restaurant_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="restaurant_photos/"
            ),
        ),
    ]
