# Generated by Django 5.0.6 on 2025-11-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0007_restaurant_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="price_level",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Budget"),
                    (2, "Moderate"),
                    (3, "Expensive"),
                    (4, "Luxury"),
                ],
                help_text="1 = Budget, 4 = Luxury",
                null=True,
            ),
        ),
    ]
