# Generated by Django 5.0.6 on 2025-10-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("CUSTOMER", "Customer"),
                    ("STAFF", "Staff"),
                    ("OWNER", "Owner"),
                    ("ADMIN", "Admin"),
                    ("SUPPORT", "Support"),
                ],
                default="CUSTOMER",
                max_length=16,
            ),
        ),
    ]
