# Generated by Django 5.0.6 on 2025-11-05 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_staffinvitation_role_alter_user_role"),
        ("restaurants", "0004_reservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffinvitation",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="restaurants.restaurant",
            ),
        ),
        migrations.DeleteModel(
            name="Restaurant",
        ),
    ]
